name: Benchmark
on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Typst
        uses: typst-community/setup-typst@v4

      - name: Install Hyperfine
        uses: taiki-e/install-action@v2
        with:
          tool: hyperfine

      - name: Run Hyperfine benchmark
        id: benchmark
        run: |
          hyperfine --warmup 10 --runs 100 "typst compile .github/assets/stress_test.typ --root './'" | tee benchmark_result.txt
          sed -i 's/[ \t]*$//' benchmark_result.txt
          echo "result<<EOF" >> $GITHUB_OUTPUT
          cat benchmark_result.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment with benchmark results
        uses: peter-evans/commit-comment@v3
        with:
          body: |
            **Hyperfine Benchmark Results:**
            ```
            ${{ steps.benchmark.outputs.result }}
            ```
